name: main
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Debug environment
        run: |
          pwd
          ls -la
          cat package.json || echo "package.json not found"
          npm --version
          node --version
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed"
          npm list || echo "Unable to list dependencies"
      - name: Run type check
        run: |
          echo "Checking for type script..."
          if npm run type --dry-run; then
            npm run type
          else
            echo "Type script not found in package.json"
          fi
      - name: Run lint
        run: |
          echo "Checking for lint script..."
          if npm run lint --dry-run; then
            npm run lint
          else
            echo "Lint script not found in package.json"
          fi
      - name: Run tests
        run: |
          echo "Running tests..."
          if npm run test --dry-run; then
            npm test
          else
            echo "Test script not found in package.json"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Debug environment
        run: |
          pwd
          ls -la
          cat action.yml || echo "action.yml not found"
          ls -la Dockerfile || echo "Dockerfile not found"
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
      - name: Update action.yml
        run: |
          if [ -f "action.yml" ]; then
            echo "Updating action.yml..."
            cat action.yml
            sed -i "s/image: .*/image: Dockerfile/" action.yml
            echo "Updated action.yml:"
            cat action.yml
          else
            echo "action.yml not found"
            exit 1
          fi
      - name: Prepare dist directory
        run: |
          mkdir -p dist
          ls -la dist

  test-action-svg-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Debug environment
        run: |
          pwd
          ls -la
          ls -la packages/action || echo "packages/action directory not found"
          npm list -g || echo "No global packages"
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
      - name: Build svg-only action
        run: |
          echo "Starting build:action..."
          if npm run build:action --dry-run; then
            npm run build:action
          else
            echo "build:action script not found in package.json"
            exit 1
          fi
          
          echo "Checking directories..."
          ls -la svg-only || echo "svg-only directory not found"
          ls -la packages/action/dist || echo "packages/action/dist not found"
          
          if [ -d "packages/action/dist" ]; then
            echo "Moving dist directory..."
            mkdir -p svg-only
            mv packages/action/dist svg-only/
            echo "Moved successfully"
            ls -la svg-only/dist
          else
            echo "Source directory not found"
            exit 1
          fi
